import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar.component";
import Script from "next/script";
import StoreProvider from "./StoreProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='dark'>
    <StoreProvider>    
      <Script type="text/javascript" src="https://d3js.org/d3.v4.min.js" />
      <body className={inter.className}>
        
     

        <Navbar/>
        {/* <Nav/> */}

        {children}</body>
 
    </StoreProvider>
    </html>

  );
}
